# Generated by Django 4.1.4 on 2023-01-15 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Network', '0001_initial'),
        ('Profile', '0002_profile_first_degree_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_degree',
            field=models.ManyToManyField(blank=True, related_name='first_degree', through='Network.FirstConnections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='Network.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_degree',
            field=models.ManyToManyField(blank=True, related_name='second_degree', through='Network.SecondConnections', to=settings.AUTH_USER_MODEL),
        ),
    ]
