# Generated by Django 4.1.4 on 2023-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_first_degree_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
