# Generated by Django 4.1.4 on 2022-12-22 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.BigIntegerField(default=444444, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
